version: '3'
services:
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=loansapi/api.py
      - FLASK_DEBUG=1
      - 'RUN=pipenv run flask run --host=0.0.0.0 --port=5000'
    # command: pipenv run flask run --host=0.0.0.0 --port=5000
    # Infinite loop, to keep it alive, for debugging
    command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
